import { Inter } from 'next/font/google'
import './globals.css'
import { ContextWrapper } from './context/ContextWrapper'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'consaborasinaloa',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><ContextWrapper><Header /> <div className='container-app-main'>
        {children}
      </div><Footer /></ContextWrapper></body>
    </html>
  )
}
